# Generated by Django 5.2.3 on 2026-06-18 21:15

import apps.common.fields
import django.contrib.postgres.fields
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('operators', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('notes', models.TextField(blank=True, default='')),
                ('custom_fields', models.JSONField(default=dict)),
                ('state', models.TextField(choices=[('in_use', 'In use'), ('in_storage', 'In storage'), ('pending_repair', 'Pending repair'), ('broken', 'Broken'), ('decommissioned', 'Decommissioned')], default='in_use')),
                ('device_type', models.TextField(choices=[('laptop', 'Laptop'), ('desktop', 'Desktop'), ('phone', 'Phone'), ('tablet', 'Tablet'), ('server', 'Server'), ('firewall', 'Firewall'), ('router', 'Router'), ('switch', 'Switch'), ('access_point', 'Access point'), ('controller', 'Controller'), ('printer', 'Printer'), ('other', 'Other')])),
                ('brand', models.TextField(blank=True, default='')),
                ('model', models.TextField(blank=True, default='')),
                ('serial_number', models.TextField(blank=True, null=True, unique=True)),
                ('asset_tag', models.TextField(blank=True, default='')),
                ('cpu', models.TextField(blank=True, default='')),
                ('ram_gb', models.IntegerField(blank=True, null=True)),
                ('storage_gb', models.IntegerField(blank=True, null=True)),
                ('storage_type', models.TextField(blank=True, default='')),
                ('hostname', models.TextField(blank=True, default='')),
                ('mac_addresses', django.contrib.postgres.fields.ArrayField(base_field=apps.common.fields.MACAddressField(), blank=True, null=True, size=None)),
                ('ip_addresses', django.contrib.postgres.fields.ArrayField(base_field=models.GenericIPAddressField(), blank=True, null=True, size=None)),
                ('purchase_date', models.DateField(blank=True, null=True)),
                ('warranty_expiry', models.DateField(blank=True, null=True)),
                ('vendor', models.TextField(blank=True, default='')),
                ('created_by', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='operators.operator')),
                ('updated_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='operators.operator')),
            ],
            options={
                'db_table': 'device',
            },
        ),
        migrations.CreateModel(
            name='FieldDefinition',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('entity_type', models.TextField(choices=[('person', 'Person'), ('account', 'Account'), ('device', 'Device'), ('office', 'Office')])),
                ('key', models.TextField()),
                ('label', models.TextField()),
                ('data_type', models.TextField(choices=[('string', 'String'), ('integer', 'Integer'), ('date', 'Date'), ('boolean', 'Boolean'), ('select', 'Select'), ('multiselect', 'Multi-select')])),
                ('options', models.JSONField(blank=True, null=True)),
                ('required', models.BooleanField(default=False)),
                ('viewer_visible', models.BooleanField(default=True)),
                ('display_order', models.IntegerField(default=0)),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'field_definition',
                'constraints': [models.UniqueConstraint(fields=('entity_type', 'key'), name='field_definition_entity_key_unique'), models.CheckConstraint(condition=models.Q(('entity_type__in', ['person', 'account', 'device', 'office'])), name='field_definition_entity_type_valid'), models.CheckConstraint(condition=models.Q(('data_type__in', ['string', 'integer', 'date', 'boolean', 'select', 'multiselect'])), name='field_definition_data_type_valid')],
            },
        ),
        migrations.CreateModel(
            name='Office',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('notes', models.TextField(blank=True, default='')),
                ('custom_fields', models.JSONField(default=dict)),
                ('state', models.TextField(choices=[('active', 'Active'), ('in_setup', 'In setup'), ('closed', 'Closed')], default='active')),
                ('name', models.TextField()),
                ('address', models.TextField(blank=True, default='')),
                ('isp', models.TextField(blank=True, default='')),
                ('created_by', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='operators.operator')),
                ('updated_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='operators.operator')),
            ],
            options={
                'db_table': 'office',
            },
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('notes', models.TextField(blank=True, default='')),
                ('custom_fields', models.JSONField(default=dict)),
                ('state', models.TextField(choices=[('active', 'Active'), ('suspended', 'Suspended'), ('offboarding', 'Offboarding'), ('terminated', 'Terminated')], default='active')),
                ('full_name', models.TextField()),
                ('internal_code', models.TextField(blank=True, null=True, unique=True)),
                ('job_title', models.TextField(blank=True, default='')),
                ('department', models.TextField(blank=True, default='')),
                ('personal_email', models.TextField(blank=True, default='')),
                ('phone', models.TextField(blank=True, default='')),
                ('extension', models.TextField(blank=True, default='')),
                ('hire_date', models.DateField(blank=True, null=True)),
                ('exit_date', models.DateField(blank=True, null=True)),
                ('created_by', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='operators.operator')),
                ('operator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='operators.operator')),
                ('updated_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='operators.operator')),
            ],
            options={
                'db_table': 'person',
            },
        ),
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('notes', models.TextField(blank=True, default='')),
                ('custom_fields', models.JSONField(default=dict)),
                ('state', models.TextField(choices=[('active', 'Active'), ('disabled', 'Disabled'), ('compromised', 'Compromised'), ('needs_rotation', 'Needs rotation')], default='active')),
                ('account_type', models.TextField(choices=[('o365', 'Office 365'), ('ms_personal', 'Microsoft personal'), ('google', 'Google'), ('samsung', 'Samsung'), ('apple_id', 'Apple ID'), ('odoo', 'Odoo'), ('network_admin', 'Network admin'), ('external_service', 'External service'), ('other', 'Other')])),
                ('label', models.TextField()),
                ('identifier', models.TextField()),
                ('mfa_state', models.TextField(choices=[('enabled', 'Enabled'), ('disabled', 'Disabled'), ('unknown', 'Unknown')], default='unknown')),
                ('mfa_types', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('authenticator_app', 'Authenticator app'), ('sms', 'SMS'), ('voice', 'Voice'), ('email', 'Email'), ('hardware_key', 'Hardware key'), ('windows_hello', 'Windows Hello'), ('passkey', 'Passkey'), ('unknown', 'Unknown')], max_length=32), blank=True, null=True, size=None)),
                ('recovery_email', models.TextField(blank=True, default='')),
                ('recovery_phone', models.TextField(blank=True, default='')),
                ('last_password_change', models.DateField(blank=True, null=True)),
                ('external_source', models.TextField(blank=True, default='')),
                ('external_id', models.TextField(blank=True, null=True)),
                ('created_by', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='operators.operator')),
                ('updated_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='operators.operator')),
            ],
            options={
                'db_table': 'account',
                'indexes': [models.Index(fields=['state'], name='account_state_idx'), models.Index(fields=['mfa_state'], name='account_mfa_state_idx'), models.Index(fields=['account_type'], name='account_type_idx'), models.Index(fields=['external_id'], name='account_external_id_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('state__in', ['active', 'disabled', 'compromised', 'needs_rotation'])), name='account_state_valid'), models.CheckConstraint(condition=models.Q(('account_type__in', ['o365', 'ms_personal', 'google', 'samsung', 'apple_id', 'odoo', 'network_admin', 'external_service', 'other'])), name='account_type_valid'), models.CheckConstraint(condition=models.Q(('mfa_state__in', ['enabled', 'disabled', 'unknown'])), name='account_mfa_state_valid')],
            },
        ),
        migrations.CreateModel(
            name='NetworkDeviceDetail',
            fields=[
                ('device', models.OneToOneField(db_column='device_id', on_delete=django.db.models.deletion.PROTECT, primary_key=True, related_name='network_detail', serialize=False, to='inventory.device')),
                ('firmware_version', models.TextField(blank=True, default='')),
                ('last_firmware_update', models.DateField(blank=True, null=True)),
                ('monitoring_method', models.TextField(choices=[('snmp', 'SNMP'), ('api', 'API'), ('none', 'None')], default='none')),
                ('monitoring_endpoint', models.TextField(blank=True, default='')),
                ('management_url', models.TextField(blank=True, default='')),
                ('health_state', models.TextField(choices=[('reachable', 'Reachable'), ('alerting', 'Alerting'), ('offline', 'Offline'), ('unknown', 'Unknown')], default='unknown')),
                ('last_seen_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'network_device_detail',
                'indexes': [models.Index(fields=['health_state'], name='netdev_health_idx'), models.Index(fields=['last_seen_at'], name='netdev_last_seen_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('monitoring_method__in', ['snmp', 'api', 'none'])), name='netdev_monitoring_method_valid'), models.CheckConstraint(condition=models.Q(('health_state__in', ['reachable', 'alerting', 'offline', 'unknown'])), name='netdev_health_state_valid')],
            },
        ),
        migrations.AddIndex(
            model_name='device',
            index=models.Index(fields=['state'], name='device_state_idx'),
        ),
        migrations.AddIndex(
            model_name='device',
            index=models.Index(fields=['device_type'], name='device_type_idx'),
        ),
        migrations.AddIndex(
            model_name='device',
            index=models.Index(fields=['warranty_expiry'], name='device_warranty_idx'),
        ),
        migrations.AddConstraint(
            model_name='device',
            constraint=models.CheckConstraint(condition=models.Q(('state__in', ['in_use', 'in_storage', 'pending_repair', 'broken', 'decommissioned'])), name='device_state_valid'),
        ),
        migrations.AddConstraint(
            model_name='device',
            constraint=models.CheckConstraint(condition=models.Q(('device_type__in', ['laptop', 'desktop', 'phone', 'tablet', 'server', 'firewall', 'router', 'switch', 'access_point', 'controller', 'printer', 'other'])), name='device_type_valid'),
        ),
        migrations.AddConstraint(
            model_name='office',
            constraint=models.CheckConstraint(condition=models.Q(('state__in', ['active', 'in_setup', 'closed'])), name='office_state_valid'),
        ),
        migrations.AddIndex(
            model_name='person',
            index=models.Index(fields=['state'], name='person_state_idx'),
        ),
        migrations.AddConstraint(
            model_name='person',
            constraint=models.CheckConstraint(condition=models.Q(('state__in', ['active', 'suspended', 'offboarding', 'terminated'])), name='person_state_valid'),
        ),
    ]
