# Generated by Django 5.2.3 on 2026-06-18 21:15

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Operator',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('username', models.TextField(unique=True)),
                ('display_name', models.TextField()),
                ('role', models.TextField(choices=[('administrator', 'Administrator'), ('viewer', 'Viewer')])),
                ('password_hash', models.TextField()),
                ('is_active', models.BooleanField(default=True)),
                ('last_login_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'operator',
                'constraints': [models.CheckConstraint(condition=models.Q(('role__in', ['administrator', 'viewer'])), name='operator_role_valid')],
            },
        ),
        migrations.CreateModel(
            name='OperatorWebAuthnCredential',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('credential_id', models.BinaryField()),
                ('public_key', models.BinaryField()),
                ('sign_count', models.BigIntegerField(default=0)),
                ('label', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_used_at', models.DateTimeField(blank=True, null=True)),
                ('operator', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='webauthn_credentials', to='operators.operator')),
            ],
            options={
                'db_table': 'operator_webauthn_credential',
                'constraints': [models.UniqueConstraint(fields=('credential_id',), name='operator_webauthn_credential_id_unique')],
            },
        ),
    ]
