# Generated by Django 5.2.3 on 2026-06-18 22:02

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operators', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OperatorSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('token_hash', models.TextField()),
                ('ip', models.GenericIPAddressField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_activity_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('operator', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sessions', to='operators.operator')),
            ],
            options={
                'db_table': 'operator_session',
            },
        ),
        migrations.CreateModel(
            name='SessionRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('state', models.TextField(choices=[('pending', 'Pending'), ('granted', 'Granted'), ('denied', 'Denied'), ('expired', 'Expired'), ('cancelled', 'Cancelled')], default='pending')),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('current_session', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='requests', to='operators.operatorsession')),
                ('requested_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='session_requests', to='operators.operator')),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='operators.operator')),
            ],
            options={
                'db_table': 'session_request',
            },
        ),
        migrations.AddIndex(
            model_name='operatorsession',
            index=models.Index(fields=['operator', 'revoked_at'], name='operator_session_active_idx'),
        ),
        migrations.AddConstraint(
            model_name='sessionrequest',
            constraint=models.CheckConstraint(condition=models.Q(('state__in', ['pending', 'granted', 'denied', 'expired', 'cancelled'])), name='session_request_state_valid'),
        ),
    ]
