# Generated by Django 5.2.3 on 2026-06-19 03:13

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operators', '0002_operatorsession_sessionrequest_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='OperatorTotpDevice',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('ciphertext', models.BinaryField()),
                ('nonce', models.BinaryField()),
                ('dek_wrapped', models.BinaryField()),
                ('dek_nonce', models.BinaryField()),
                ('confirmed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('operator', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='totp_device', to='operators.operator')),
            ],
            options={
                'db_table': 'operator_totp_device',
            },
        ),
    ]
