# Generated by Django 5.2.3 on 2026-06-18 21:52

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventory', '0001_initial'),
        ('operators', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountDeviceConfig',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('state', models.TextField(choices=[('active', 'Active'), ('former', 'Former')], default='active')),
                ('valid_from', models.DateTimeField(default=django.utils.timezone.now)),
                ('valid_to', models.DateTimeField(blank=True, null=True)),
                ('purpose', models.TextField(choices=[('setup', 'Setup'), ('mail', 'Mail'), ('mdm', 'MDM'), ('other', 'Other')], default='other')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='device_configs', to='inventory.account')),
                ('created_by', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='operators.operator')),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='account_configs', to='inventory.device')),
                ('updated_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='operators.operator')),
            ],
            options={
                'db_table': 'account_device_config',
                'constraints': [models.CheckConstraint(condition=models.Q(('state__in', ['active', 'former'])), name='account_device_config_state_valid'), models.CheckConstraint(condition=models.Q(('purpose__in', ['setup', 'mail', 'mdm', 'other'])), name='account_device_config_purpose_valid')],
            },
        ),
        migrations.CreateModel(
            name='AccountOwnership',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('state', models.TextField(choices=[('active', 'Active'), ('former', 'Former')], default='active')),
                ('valid_from', models.DateTimeField(default=django.utils.timezone.now)),
                ('valid_to', models.DateTimeField(blank=True, null=True)),
                ('role', models.TextField(choices=[('primary', 'Primary'), ('shared', 'Shared')], default='shared')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ownerships', to='inventory.account')),
                ('created_by', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='operators.operator')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='account_ownerships', to='inventory.person')),
                ('updated_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='operators.operator')),
            ],
            options={
                'db_table': 'account_ownership',
                'constraints': [models.CheckConstraint(condition=models.Q(('state__in', ['active', 'former'])), name='account_ownership_state_valid'), models.CheckConstraint(condition=models.Q(('role__in', ['primary', 'shared'])), name='account_ownership_role_valid'), models.UniqueConstraint(condition=models.Q(('role', 'primary'), ('state', 'active')), fields=('account',), name='account_ownership_one_active_primary')],
            },
        ),
        migrations.CreateModel(
            name='AccountRecovery',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('state', models.TextField(choices=[('active', 'Active'), ('former', 'Former')], default='active')),
                ('valid_from', models.DateTimeField(default=django.utils.timezone.now)),
                ('valid_to', models.DateTimeField(blank=True, null=True)),
                ('priority', models.IntegerField(default=0)),
                ('created_by', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='operators.operator')),
                ('recovery_account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='recovery_for', to='inventory.account')),
                ('target_account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='recovery_accounts', to='inventory.account')),
                ('updated_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='operators.operator')),
            ],
            options={
                'db_table': 'account_recovery',
                'constraints': [models.CheckConstraint(condition=models.Q(('state__in', ['active', 'former'])), name='account_recovery_state_valid'), models.CheckConstraint(condition=models.Q(('recovery_account', models.F('target_account')), _negated=True), name='account_recovery_distinct')],
            },
        ),
        migrations.CreateModel(
            name='AccountRecoveryContact',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('state', models.TextField(choices=[('active', 'Active'), ('former', 'Former')], default='active')),
                ('valid_from', models.DateTimeField(default=django.utils.timezone.now)),
                ('valid_to', models.DateTimeField(blank=True, null=True)),
                ('channel', models.TextField(choices=[('email', 'Email'), ('phone', 'Phone'), ('other', 'Other')], default='email')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='recovery_contacts', to='inventory.account')),
                ('created_by', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='operators.operator')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='account_recovery_contacts', to='inventory.person')),
                ('updated_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='operators.operator')),
            ],
            options={
                'db_table': 'account_recovery_contact',
                'constraints': [models.CheckConstraint(condition=models.Q(('state__in', ['active', 'former'])), name='account_recovery_contact_state_valid'), models.CheckConstraint(condition=models.Q(('channel__in', ['email', 'phone', 'other'])), name='account_recovery_contact_channel_valid')],
            },
        ),
        migrations.CreateModel(
            name='DeviceAssignment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('state', models.TextField(choices=[('active', 'Active'), ('former', 'Former')], default='active')),
                ('valid_from', models.DateTimeField(default=django.utils.timezone.now)),
                ('valid_to', models.DateTimeField(blank=True, null=True)),
                ('role', models.TextField(choices=[('primary_user', 'Primary user'), ('temporary', 'Temporary')], default='primary_user')),
                ('created_by', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='operators.operator')),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assignments', to='inventory.device')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='device_assignments', to='inventory.person')),
                ('updated_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='operators.operator')),
            ],
            options={
                'db_table': 'device_assignment',
                'constraints': [models.CheckConstraint(condition=models.Q(('state__in', ['active', 'former'])), name='device_assignment_state_valid'), models.CheckConstraint(condition=models.Q(('role__in', ['primary_user', 'temporary'])), name='device_assignment_role_valid'), models.UniqueConstraint(condition=models.Q(('state', 'active')), fields=('device',), name='device_assignment_one_active_holder')],
            },
        ),
        migrations.CreateModel(
            name='DeviceDependency',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('state', models.TextField(choices=[('active', 'Active'), ('former', 'Former')], default='active')),
                ('valid_from', models.DateTimeField(default=django.utils.timezone.now)),
                ('valid_to', models.DateTimeField(blank=True, null=True)),
                ('nature', models.TextField(choices=[('uplink', 'Uplink'), ('power', 'Power'), ('controller', 'Controller'), ('other', 'Other')], default='other')),
                ('created_by', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='operators.operator')),
                ('dependent_device', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='dependencies', to='inventory.device')),
                ('depends_on_device', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='dependents', to='inventory.device')),
                ('updated_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='operators.operator')),
            ],
            options={
                'db_table': 'device_dependency',
                'constraints': [models.CheckConstraint(condition=models.Q(('state__in', ['active', 'former'])), name='device_dependency_state_valid'), models.CheckConstraint(condition=models.Q(('nature__in', ['uplink', 'power', 'controller', 'other'])), name='device_dependency_nature_valid'), models.CheckConstraint(condition=models.Q(('dependent_device', models.F('depends_on_device')), _negated=True), name='device_dependency_distinct')],
            },
        ),
        migrations.CreateModel(
            name='DeviceLocation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('state', models.TextField(choices=[('active', 'Active'), ('former', 'Former')], default='active')),
                ('valid_from', models.DateTimeField(default=django.utils.timezone.now)),
                ('valid_to', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='operators.operator')),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='locations', to='inventory.device')),
                ('office', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='device_locations', to='inventory.office')),
                ('updated_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='operators.operator')),
            ],
            options={
                'db_table': 'device_location',
                'constraints': [models.CheckConstraint(condition=models.Q(('state__in', ['active', 'former'])), name='device_location_state_valid'), models.UniqueConstraint(condition=models.Q(('state', 'active')), fields=('device',), name='device_location_one_active')],
            },
        ),
        migrations.CreateModel(
            name='DeviceRecoveryContact',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('state', models.TextField(choices=[('active', 'Active'), ('former', 'Former')], default='active')),
                ('valid_from', models.DateTimeField(default=django.utils.timezone.now)),
                ('valid_to', models.DateTimeField(blank=True, null=True)),
                ('channel', models.TextField(choices=[('email', 'Email'), ('phone', 'Phone'), ('other', 'Other')], default='email')),
                ('created_by', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='operators.operator')),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='recovery_contacts', to='inventory.device')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='device_recovery_contacts', to='inventory.person')),
                ('updated_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='operators.operator')),
            ],
            options={
                'db_table': 'device_recovery_contact',
                'constraints': [models.CheckConstraint(condition=models.Q(('state__in', ['active', 'former'])), name='device_recovery_contact_state_valid'), models.CheckConstraint(condition=models.Q(('channel__in', ['email', 'phone', 'other'])), name='device_recovery_contact_channel_valid')],
            },
        ),
        migrations.CreateModel(
            name='OfficeMembership',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('state', models.TextField(choices=[('active', 'Active'), ('former', 'Former')], default='active')),
                ('valid_from', models.DateTimeField(default=django.utils.timezone.now)),
                ('valid_to', models.DateTimeField(blank=True, null=True)),
                ('role', models.TextField(choices=[('staff', 'Staff'), ('responsible', 'Responsible')], default='staff')),
                ('created_by', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='operators.operator')),
                ('office', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='memberships', to='inventory.office')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='office_memberships', to='inventory.person')),
                ('updated_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='operators.operator')),
            ],
            options={
                'db_table': 'office_membership',
                'constraints': [models.CheckConstraint(condition=models.Q(('state__in', ['active', 'former'])), name='office_membership_state_valid'), models.CheckConstraint(condition=models.Q(('role__in', ['staff', 'responsible'])), name='office_membership_role_valid'), models.UniqueConstraint(condition=models.Q(('role', 'responsible'), ('state', 'active')), fields=('office',), name='office_membership_one_responsible')],
            },
        ),
    ]
