# Generated by Django 5.2.3 on 2026-06-18 23:54

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('operators', '0002_operatorsession_sessionrequest_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditCheckpoint',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('seq', models.BigIntegerField()),
                ('head_hash', models.BinaryField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('signature', models.BinaryField(blank=True, null=True)),
                ('signer', models.TextField(blank=True, default='')),
                ('external_anchor_ref', models.TextField(blank=True, default='')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='operators.operator')),
            ],
            options={
                'db_table': 'audit_checkpoint',
            },
        ),
        migrations.CreateModel(
            name='AuditEntry',
            fields=[
                ('seq', models.BigIntegerField(primary_key=True, serialize=False)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('occurred_at', models.DateTimeField()),
                ('recorded_at', models.DateTimeField(auto_now_add=True)),
                ('actor_type', models.TextField(choices=[('operator', 'Operator'), ('system', 'System')])),
                ('actor_username', models.TextField(blank=True, default='')),
                ('source_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('action', models.TextField(choices=[('create', 'Create'), ('update', 'Update'), ('state_change', 'State change'), ('relationship_create', 'Relationship create'), ('relationship_end', 'Relationship end'), ('secret_create', 'Secret create'), ('secret_rotate', 'Secret rotate'), ('secret_reveal', 'Secret reveal'), ('secret_state_change', 'Secret state change'), ('login_success', 'Login success'), ('login_failure', 'Login failure'), ('logout', 'Logout'), ('vault_unlock', 'Vault unlock'), ('vault_lock', 'Vault lock'), ('session_revoke', 'Session revoke'), ('reauth', 'Re-auth'), ('field_definition_change', 'Field definition change'), ('operator_change', 'Operator change'), ('parameter_change', 'Parameter change'), ('export', 'Export'), ('record_view', 'Record view'), ('list_view', 'List view'), ('search', 'Search'), ('chain_verify', 'Chain verify'), ('checkpoint_created', 'Checkpoint created')])),
                ('target_table', models.TextField(blank=True, default='')),
                ('target_id', models.UUIDField(blank=True, null=True)),
                ('target_label', models.TextField(blank=True, default='')),
                ('changes', models.JSONField(default=dict)),
                ('metadata', models.JSONField(default=dict)),
                ('prev_hash', models.BinaryField()),
                ('entry_hash', models.BinaryField()),
                ('hash_algo', models.TextField(default='blake2b-256')),
                ('scheme_version', models.IntegerField(default=1)),
                ('actor_operator', models.ForeignKey(blank=True, db_column='actor_operator_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='operators.operator')),
                ('session', models.ForeignKey(blank=True, db_column='session_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='operators.operatorsession')),
            ],
            options={
                'db_table': 'audit_entry',
                'indexes': [models.Index(fields=['target_table', 'target_id'], name='audit_target_idx'), models.Index(fields=['action'], name='audit_action_idx'), models.Index(fields=['occurred_at'], name='audit_occurred_idx')],
                'constraints': [models.UniqueConstraint(fields=('entry_hash',), name='audit_entry_hash_unique'), models.CheckConstraint(condition=models.Q(('actor_type__in', ['operator', 'system'])), name='audit_actor_type_valid'), models.CheckConstraint(condition=models.Q(('action__in', ['create', 'update', 'state_change', 'relationship_create', 'relationship_end', 'secret_create', 'secret_rotate', 'secret_reveal', 'secret_state_change', 'login_success', 'login_failure', 'logout', 'vault_unlock', 'vault_lock', 'session_revoke', 'reauth', 'field_definition_change', 'operator_change', 'parameter_change', 'export', 'record_view', 'list_view', 'search', 'chain_verify', 'checkpoint_created'])), name='audit_action_valid')],
            },
        ),
    ]
