# Generated by Django 5.2.3 on 2026-06-19 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0002_append_only'),
    ]

    operations = [
        migrations.AddField(
            model_name='auditcheckpoint',
            name='signature_algo',
            field=models.TextField(blank=True, default=''),
        ),
    ]
