# Generated by Django 5.2.3 on 2026-06-18 21:15

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('operators', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Secret',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner_type', models.TextField(choices=[('account', 'Account'), ('device', 'Device'), ('office', 'Office'), ('operator', 'Operator'), ('integration', 'Integration')])),
                ('owner_id', models.UUIDField()),
                ('kind', models.TextField(choices=[('password', 'Password'), ('recovery_codes', 'Recovery codes'), ('pin', 'PIN'), ('passphrase', 'Passphrase'), ('api_key', 'API key'), ('wifi_psk', 'Wi-Fi PSK'), ('bios_password', 'BIOS password'), ('disk_recovery_key', 'Disk recovery key'), ('totp_seed', 'TOTP seed'), ('snmp_community', 'SNMP community'), ('other', 'Other')])),
                ('label', models.TextField(blank=True, default='')),
                ('ciphertext', models.BinaryField()),
                ('nonce', models.BinaryField()),
                ('dek_wrapped', models.BinaryField()),
                ('dek_nonce', models.BinaryField()),
                ('aad_context', models.TextField()),
                ('scheme_version', models.IntegerField(default=1)),
                ('last_rotated_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='operators.operator')),
                ('updated_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='operators.operator')),
            ],
            options={
                'db_table': 'secret',
                'indexes': [models.Index(fields=['owner_type', 'owner_id'], name='secret_owner_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('owner_type__in', ['account', 'device', 'office', 'operator', 'integration'])), name='secret_owner_type_valid'), models.CheckConstraint(condition=models.Q(('kind__in', ['password', 'recovery_codes', 'pin', 'passphrase', 'api_key', 'wifi_psk', 'bios_password', 'disk_recovery_key', 'totp_seed', 'snmp_community', 'other'])), name='secret_kind_valid')],
            },
        ),
    ]
