# Generated by Django 5.2.3 on 2026-06-18 23:25

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operators', '0002_operatorsession_sessionrequest_and_more'),
        ('vault', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VaultKeyHolder',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('kdf_salt', models.BinaryField()),
                ('kdf_memory', models.IntegerField()),
                ('kdf_iterations', models.IntegerField()),
                ('kdf_parallelism', models.IntegerField()),
                ('scheme_version', models.IntegerField(default=1)),
                ('mk_wrapped', models.BinaryField()),
                ('mk_nonce', models.BinaryField()),
                ('second_factor_ref', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='operators.operator')),
                ('operator', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='vault_key_holder', to='operators.operator')),
            ],
            options={
                'db_table': 'vault_key_holder',
            },
        ),
    ]
