# Generated by Django 5.2.3 on 2026-06-18 23:37

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operators', '0002_operatorsession_sessionrequest_and_more'),
        ('vault', '0002_vaultkeyholder'),
    ]

    operations = [
        migrations.CreateModel(
            name='VaultRecoveryKey',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('rk_wrapped', models.BinaryField()),
                ('rk_nonce', models.BinaryField()),
                ('fingerprint', models.TextField()),
                ('scheme_version', models.IntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='operators.operator')),
            ],
            options={
                'db_table': 'vault_recovery_key',
            },
        ),
    ]
