# Generated by Django 5.2.3 on 2026-06-19 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operators', '0003_operatortotpdevice'),
        ('vault', '0003_vaultrecoverykey'),
    ]

    operations = [
        migrations.AddField(
            model_name='secret',
            name='state',
            field=models.TextField(choices=[('active', 'Active'), ('archived', 'Archived')], default='active'),
        ),
        migrations.AddConstraint(
            model_name='secret',
            constraint=models.CheckConstraint(condition=models.Q(('state__in', ['active', 'archived'])), name='secret_state_valid'),
        ),
    ]
